# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dept_libraryC',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='labC',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='profC',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='wardenC',
            field=models.CharField(default='', max_length=700),
        ),
    ]
