# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20161118_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proffesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='proffesor', max_length=70)),
                ('webmail', models.CharField(default='mailprof', max_length=30)),
                ('hostel', models.CharField(default='NIL', max_length=700)),
                ('hod', models.BooleanField(default=0)),
                ('colName', models.CharField(default='prof', max_length=700)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='dept_library',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dept_libraryC',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='student',
            name='labC',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profC',
        ),
        migrations.RemoveField(
            model_name='student',
            name='warden',
        ),
        migrations.RemoveField(
            model_name='student',
            name='wardenC',
        ),
        migrations.AddField(
            model_name='student',
            name='hostel',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='hostelC',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='prof1',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='prof1C',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='prof2',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='prof2C',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='prof3',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='prof3C',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='prof4',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='prof4C',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='student', max_length=70),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(default='15010106', max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='webmail',
            field=models.CharField(default='mail', max_length=30),
        ),
    ]
