# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20161119_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='prof4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prof4C',
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.CharField(default='barak', max_length=50),
        ),
    ]
