# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20161122_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='other', max_length=70)),
                ('webmail', models.CharField(default='mailother', max_length=30)),
                ('colName', models.CharField(default='lab', max_length=700)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='lab1',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='lab1C',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='lab2',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='lab2C',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='lab3',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='lab3C',
            field=models.CharField(default='No remarks', max_length=700),
        ),
    ]
