# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20161126_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cc',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='ccC',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='cenlib',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='cenlibC',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='cselib',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='cselibC',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='fa',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='faC',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='sa',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='saC',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='workshop',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='workshopC',
            field=models.CharField(default='No remarks', max_length=700),
        ),
    ]
