# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20161126_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prof4',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='prof4C',
            field=models.CharField(default='No remarks', max_length=700),
        ),
        migrations.AddField(
            model_name='student',
            name='prof5',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='prof5C',
            field=models.CharField(default='No remarks', max_length=700),
        ),
    ]
